[package]
org = "evento-globolo"
name = "evgl-mash-web"
version = "0.1.0"
description = "Rust web server for Evento Globolo"
license = "MIT"
language = "rust"

[package.repository]
vcs = "git"
url = "https://github.com/evento-globolo/evgl-mash-web"

[install]
dir = ".vendor/.zed"

[dependencies]
"evento-globolo/evgl-interfaces" = "^0.1.0"
"evento-globolo/evgl-libs" = "^0.1.0"

[publish]
include_readme = true
tag_format = "v{version}"
exclude = [".env", ".env.*", "node_modules/**", "target/**", "dist/**", "*.log", ".vendor/.zed/**"]
